### ISSUE TITLE
error when installed from chrome store:"manifest file is invalid"

### ISSUE THREAD

**Issue by altkatz** [hewigovens/BookmarkSpell#1]

**Comment by hewigovens** [comment]
What's your chrome version? BookmarkSpell use manifest v2. please try install with latest chrome, good luck,:)

**Comment by altkatz** [comment]
@hewigovens 
Version 28.0.1500.95. on Linux

**Comment by hewigovens** [comment]
@eq42
I tested with Chrome 28 on CentOS6, seems ok. BTW, Did you set proxy when installing extension from Chrome Web Store?

**Comment by altkatz** [comment]
@hewigovens  It works after SwitchySharp is disabled. Thanks. So the acess to chrome proxy is exclusive, right?

**Comment by hewigovens** [comment]
@eq42 I think this may be caused by your proxy, It seems the downloaded crx file is not valid. you can try another proxy...
